name: test_Docker
on: [push]
jobs:
 build_run:
  runs-on: ubuntu-latest  
  steps:
  
    - name: build_run_project
      run: |
        docker build -t hello_world .
        mkdir tests
        docker run hello_world > tests/test.txt
        cat tests/test.txt
